# Generated by Django 3.0.7 on 2020-06-17 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0004_auto_20200617_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='friend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='borrowed_books', to='p_library.Friend'),
        ),
    ]
