# Generated by Django 3.0.7 on 2020-06-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0008_auto_20200625_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='copy_count',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
    ]
